# Generated by Django 4.2.3 on 2023-08-08 17:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0005_employee_employee_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultancy',
            fields=[
                ('c_id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('c_password', models.CharField(max_length=45)),
                ('c_name', models.CharField(max_length=45)),
                ('phone', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=45)),
                ('description', models.TextField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
